### ISSUE TITLE
Hard to read because of overhead information

### ISSUE THREAD

**Issue by Akku** [mstum/xcom2#1]
The information about the different difficulties might be easier to read if you aggregated all the levels were there are the same resources needed to create ... which is usually the case for all but legendary. IMHO, the v3 was much easier to read and understand mainly because of there "redundant" table rows.

**Comment by mstum** [comment]
Someone made a website, which is awesome: https://darosh.github.io/xcom2-tech-tree/

**Comment by Akku** [comment]
Really awesome :+1:
